# Camera
CAMERA_INDEX = 1

# Window
WINDOW_NAME = "PrivacyGuard AI"

# YOLO
MODEL_PATH = "yolo11n.pt"
CONFIDENCE_THRESHOLD = 0.45
IMAGE_SIZE = 640
PERSON_CLASS = 0
USE_GPU = True

# Face Recognition
FACE_RECOGNITION_INTERVAL = 15
FACE_SIMILARITY_THRESHOLD = 0.60

# Gaze

GAZE_MODEL_PATH = "models/l2cs/L2CSNet_gaze360.pkl"

GAZE_USE_GPU = USE_GPU
GAZE_INPUT_SIZE = (448, 448)
GAZE_NORMALIZATION_MEAN = (0.485, 0.456, 0.406)
GAZE_NORMALIZATION_STD = (0.229, 0.224, 0.225)

# L2CS-Net predicts a probability distribution over equally spaced angle bins.
GAZE_BIN_COUNT = 90
GAZE_BIN_SIZE_DEGREES = 4.0
GAZE_BIN_OFFSET_DEGREES = -180.0

# The laptop-screen region in the camera coordinate system, in degrees.
SCREEN_YAW_MIN = -12.0

SCREEN_YAW_MAX = 12.0

SCREEN_PITCH_MIN = -10.0

SCREEN_PITCH_MAX = 8.0

# COCO Classes

PERSON_CLASS = 0
TV_MONITOR_CLASS = 62
LAPTOP_CLASS = 63
CELL_PHONE_CLASS = 67

TRACK_CLASSES = [
    PERSON_CLASS,
    TV_MONITOR_CLASS,
    LAPTOP_CLASS,
    CELL_PHONE_CLASS,
]
